### ISSUE TITLE
Grammar, broken link

### ISSUE THREAD

**Issue by logemerson** [learn-co-students/web-auth-readme-v-000#326]
**1.**
<img width="925" alt="screen shot 2017-11-27 at 9 06 40 am" src="https://user-images.githubusercontent.com/28125427/33271084-3d296b4a-d354-11e7-862e-97266ed61c40.png">
Issue: "we have whole other problems" => "we have a whole lot of other problems" OR "we have other problems"

**2.** 
<img width="982" alt="screen shot 2017-11-27 at 9 19 49 am" src="https://user-images.githubusercontent.com/28125427/33271087-40a84868-d354-11e7-9afb-cf09f177752b.png">
Issue: The provided link returns a 404.

**Comment by atxrenegade** [comment]
"friends list" link in documentation - target: https://developer.foursquare.com/docs/explore#req=users/self/friends

results in:
broken link: 404
https://developer.foursquare.com/docs/404#req=users/self/friends

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
