### ISSUE TITLE
Missing call to render 'friends'

### ISSUE THREAD

**Issue by rjcolmed** [learn-co-students/web-auth-readme-v-000#331]
The penultimate code snippet is missing a call to `render 'friends'`, which would correctly render the template at `views/searches/friends.html.erb` after successfully hitting the searches controller's #friends action.  See attached screenshot.

<img width="937" alt="screen shot 2017-11-29 at 12 09 27 pm" src="https://user-images.githubusercontent.com/31011134/33388691-a227f538-d4fe-11e7-90df-0e84ef056e65.png">

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
